name:       MRJP-latte
version:    0.1.0.0
github:     "earlgreyz/MRJP-latte"
license:    BSD3
author:     "Mikołaj Walczak"
maintainer: "mw371852@students.mimuw.edu.pl"
copyright:  "2019 Mikołaj Walczak"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/earlgreyz/MRJP-latte#readme>

dependencies:
- base >= 4.7 && < 5
- array
- mtl
- containers

executables:
  latc_x86:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
